### ISSUE TITLE
I am unable to push a test file in this new Repository

### ISSUE THREAD

**Issue by deboprio** [sabyamon/bitaak-designs#2]
Debapriya@DEB_KRITI /e/Alumni_2016 (master)
$ git push origin master
Username for 'https://github.com': deboprio
Password for 'https://deboprio@github.com':
remote: Permission to sabyamon/bitaak-designs.git denied to deboprio.
fatal: unable to access 'https://github.com/sabyamon/bitaak-designs/': The reque
sted URL returned error: 403

**Comment by sabyamon** [comment]
@deboprio - u good now ?

**Comment by deboprio** [comment]
$ git push origin master
Username for 'https://github.com': deboprio
Password for 'https://deboprio@github.com':
To https://github.com/sabyamon/bitaak-designs
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/sabyamon/bitaak-designs'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

This is the error I am receiving now.
Also I have deleted the forked repository deboprio/bitaak-designs

**Comment by deboprio** [comment]
Resolved - 
My working directory was - E:/Alumni_2016.Where I had added the file "README.txt".When I tried to push from there it was not working.I then copied the file from the directory "Alumni_2016" to  directory Repo_Git/bitaak-designs that I had cloned this morning.Then I ran - 
`git add README.txt -m 
git status
git commit -m "test addition from deboprio"
git push origin master`
and the file got added.
